.github/workflows/presubmit.yaml
Makefile
go.mod
go.sum

feat: Added presubmit

---

.github/workflows/presubmit.yaml

fix: remove install-deps

---

go.mod
go.sum
object/object.go
status/controller.go
status/metrics.go
test/environment.go
test/object.go

feat: Added test libraries and some object utils

---

.github/workflows/postsubmit.yaml

fix: a poorly named action

---

context/context.go

Create a common context useful for operators, with helpers to inject and remove singletons from the context.

feat: added context

---

go.mod
mock/atomic.go
mock/function.go

Add mockable functions, useful for building mocks.
I made atomic internal for now, even though I think we may eventually want to expose something like it publicly.

feat: Added mocked functions

---

.github/dependabot.yaml
go.mod

This adds support for dependabot updating the dependencies 

ci: Add support for dependabot

---

go.mod

Pin to patch version of go in `go.mod`

chore: Pin to patch version of go in go.mod

---

test/expectations/expectations.go

Useful for testing the new controller-runtime approach: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#AsReconciler

feat: Add ExpectObjectReconciled

---

status/controller.go
status/controller_test.go

Simplify how generics are used for the status controller

chore: Made status controller generic

---

status/condition_set.go
status/condition_set_test.go
status/controller.go
status/controller_test.go
test/expectations/expectations.go

Adds a function to check to see if the expected conditions exist on the object

add expectation for status

---

controller/controller.go
singleton/controller.go

Add the `controller.Controller` interface and `singleton.RequeueImmediately` concepts

chore: Add controller interface and Requeue Immediately concepts

---

option/function.go
option/function_test.go
option/suite_test.go

Implements a generic for: https://golang.cafe/blog/golang-functional-options-pattern.html

feat: Added option library

---

status/controller.go
status/controller_test.go

Fixes race condition when reconciling different status conditions concurrently. This ensures that we use a sync.Map to access the status conditions so that simultaneous access across different requests is thread-safe
```
Will run 1 of 5 specs
SSSSfatal error: concurrent map read and map write
goroutine 88 [running]:
github.com/awslabs/operatorpkg/status.(*Controller[...]).Reconcile(0x10650f220, {0x106508020, 0x140005964e0}, {{{0x14000011878, 0x7}, {0x14000361f60, 0x1b}}})
/Users/joinnis/github/operatorpkg/status/controller.go:83 +0x168
github.com/awslabs/operatorpkg/test/expectations.ExpectReconciled({0x106508020, 0x140005964e0}, {0x1064ef488, 0x14000596480}, {0x106517ff8, 0x140006526c0})
/Users/joinnis/github/operatorpkg/test/expectations/expectations.go:63 +0x8c …
```

fix: Fix race condition in storing observed status conditions

---

status/condition_set.go
status/condition_set_test.go

This is to add the observedGeneration for each condition

add support for observedGeneration

---

status/condition_set.go
status/condition_set_test.go

Fix lastTrasitionTime is nil when set up condition for first time

---

status/controller.go
status/controller_test.go
test/expectations/expectations.go

Adding new metrics for monitoring termination duration for objects. Metrics added -
1. operator_termination_current_time_seconds - The current amount of time in seconds that an object has been in terminating state
2. operator_termination_duration_seconds - The amount of time taken by an object to terminate completely
Added tests for the changes

chore: Add operator termination duration metrics

---

status/condition_set.go
status/condition_set_test.go

*Issue #, if available:* 
Fixes #39
Updates our status condition sort so that we always order the root status condition at the end and order the rest of the status conditions by the time that they transitioned

chore: Update sorting conditions to order root last and sort by transition time

---

test/expectations/expectations.go

Add `ExpectForceCleanedUp` to allow users to remove all resources without finalizers and with finalizers

test: Add ExpectForceCleanedUp to package

---

option/environment.go

```
option.MustGetEnv("MYVAR")
```

Added an environment variable helper

---

leaderelection/leasehijacker.go

chore: Tidied up Lease Hijacking

---

go.mod
leaderelection/leasehijacker.go
status/controller.go

fix: a race condition with election hijacking

---

status/controller.go

Track and emit events for finalizers. This is identical to how events are emitted for condition transitions.

feat: Emit events when finalizers complete

---

status/controller.go
status/controller_test.go

All additional Prometheus labels to be injected based on Kubernetes labels
```
status.NewController[*v1.NodePool](kubeClient, mgr.GetEventRecorderFor("karpenter"), status.EmitDeprecatedMetrics, WithLabels([]string{"karpenter.sh/nodepool"})),
```
Testing with Karpenter
```
➜  karpenter-provider-aws git:(main) curl localhost:8080/metrics | grep operator_nodeclaim
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  858k    0  858k    0     0   936k      0 --:--:-- --:--:-- --:--:--  935k# HELP operator_nodeclaim_status_condition_count The number of an condition for a given object, type and status. e.g. Alarm := Available=False > 0 …
```

chore: Allow additional metric labels based on Kubernetes labels

---

status/controller.go

Fix panicing on extra labels that were pushed for deprecated metrics

chore: Fix panicing on extra labels on deprecated metrics

---

status/unstructured_adapter.go

Removing `json.Marshal` and `json.Unmarshal` reduces CPU cycles that are spent deep-copying objects and using reflection. Running a high-scale test suite that utilizes this `unstructuredAdapter` shows the reduction in CPU cycles spent toward this operation.

perf: Remove `json.Marshal` and `json.Unmarshal` since it's expensive to perform constantly

---

status/controller.go

Add gauge metric labels when firing metrics

chore: Add gauge metric labels when firing metrics

---

status/metrics.go

fix: typo in metric status condition count

---

test/expectations/expectations.go

Right now ExpectDeletionTimestampSet tries to update the list of finalizers and then delete the object again even if its already been deleted. This makes the expectation idempotent

test: update ExpectDeletionTimestamp to be idempotent
