.github/workflows/postsubmit.yaml

Hydrate goproxy on push. Useful for any crawlers of goproxy, until operatorpkg has regular consumers that pull this themselves (e.g. dependabot).

chore: Add postsubmit to consume the package to hydra GOPROXY

---

object/object.go

Without this change, I'm forced to do crazy things like
```
CRDs = []**apiextensionsv1.CustomResourceDefinition{
object.Unmarshal[*apiextensionsv1.CustomResourceDefinition](bytes),
}
```
because of
```
"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1".CustomResourceDefinition does not satisfy client.Object (method DeepCopyObject has pointer receiver)
```

feat: Accept any instead of client.Object

---

context/context.go

Alias context so customers can just import a single context package.
Before
```
import (
"context"
operatorcontext "github.com/awslabs/operatorpkg/context"
)
func main() {
ctx := operatorcontext.New()
mgr := lo.Must(controllerruntime.NewManager(controllerruntime.GetConfigOrDie(), controllerruntime.Options{
BaseContext:                   func() context.Context { return ctx },
}))
}
```
After
```
import (
"github.com/awslabs/operatorpkg/context"
)
func main() {
ctx := context.New()
mgr := lo.Must(controllerruntime.NewManager(controllerruntime.GetConfigOrDie(), controllerruntime.Options{
BaseContext:                   func() context.Context { return ctx },
}))
}
```
By submitting this pull request, I confirm that you can use, modify, copy, …

Added context aliasing to simplify consumer imports

---

status/condition_set.go
status/condition_set_test.go

Adds a helper boolean to simplify caller code when modifying status conditions
This was inspired by `modified := controllerutil.SetFinalizer()`
Before
```
if !obj.StatusConditions().Get(conditionType).IsTrue() {
obj.StatusConditions().SetTrue(conditionType)
if err := c.client.Status().Update(ctx, obj); err != nil {
return reconcile.Result{}, err
}
}
```
After
```
if obj.StatusConditions().SetTrue(conditionType) {
if err := c.client.Status().Update(ctx, obj); err != nil {
return reconcile.Result{}, err
}
}
```

feat: Added a modified boolean to condition setters

---

go.mod
reasonable/reasonable.go

The controller runtime's default rate limiter is 1ms -> 1000s, which is a bit unreasonable. I borrowed the reasonable rate limiter's settings used across the Karpenter project, which is better suited for calling cloud APIs.

feat: Added a reasonable rate limiter

---

object/object.go
status/controller.go
test/expectations/expectations.go

* Use a cleaner generic approach to the status controller
* Broke apart apply and status, since it broke for any async case (e.g. integ test) where the object was modified in flight. I couldn't just use PATCH since CRDs don't support strategic merge patches, so this approach was broken if we ever needed to write values like "" or 0. :(

chore: Made status controller generic and split Apply expectations

---

test/expectations/expectations.go

Use `reconcile.AsReconciler` when call `ExpectObjectReconciled` and `ExpectObjectReconcileFailed`. Both of these methods were not actually converting to a reconciler which meant they may not have been reconciling based on the true state of what was on the apiserver. This updates these functions so that they receive a client and get the updated state from the apiserver before reconciling with `reconcile.AsReconciler`

chore: Use reconcile.AsReconciler to call ExpectObjectReconciled

---

test/expectations/expectations.go

ExpectGet now behaves more like client-go

fix: Get now correctly hydrates the object

---

status/controller_test.go
test/expectations/expectations.go

Adds an eventually function to ExpectStatusConditions. This will fill the object with a Get call, and only succeed if the status condition is eventually what we expect. 

Add eventually to ExpectStatusConditions

---

test/expectations/expectations.go

Adds test expectations for the singleton controller constructs so that we can write testing for reconciliations.

test: Add test expectations for singleton controllers

---

metrics/metrics.go

Add the ability to register client metrics with the `RegisterClientMetrics()` call.
When calling the metrics endpoint, we see the following output reflecting the updated metrics that are returned here -- which reflects the actual apiserver calls that are made (not hitting the controller-runtime cache)
```
client_go_request_duration_seconds_count{group="",kind="events",subresource="",verb="PATCH",version="v1"} 10
client_go_request_duration_seconds_count{group="",kind="nodes",subresource="",verb="DELETE",version="v1"} 12
client_go_request_duration_seconds_count{group="",kind="nodes",subresource="",verb="LIST",version="v1"} 1
client_go_request_duration_seconds_count{group="",kind="nodes",subresource="",verb="PATCH",version="v1"} 12 …
```

feat: Add client-go metrics registration to operatorpkg

---

metrics/metrics.go

Don't panic for the following requests for client-go metrics:
- `/api/v1/namespaces`
- `/api/v1/namespaces/{name}`

fix: support namespaces requests for client-go metrics

---

status/condition_set.go
status/condition_set_test.go

This adds the `SetUnknownWithReason` function so that users that have terminal sub-conditions that want to hold conditions in an Unknown state can provide additional insight around why the condition is Unknown.

feat: Add `SetUnknownWithReason` for holding terminal conditions in unknown states

---

metrics/metrics.go

Updates latency metric buckets to be more granular for `client_go_request_duration` to be more granular and cover a broader time range

chore: Update latency metric buckets

---

go.mod

Use `1.23` toolchain and compiler

chore: Bump operatorpkg to use go 1.23

---

reasonable/reasonable.go

With the update to `k8s.io` packages on `v0.31.0`, we can now update to use the TypedRateLimiter

chore: Update to use a `TypedRateLimiter`

---

status/controller.go

https://github.com/kubernetes-sigs/controller-runtime/pull/2902 breaks some downstream integrations that use the status controller if the status controller is registered multiple times
```
panic: controller with name status already exists. Controller names must be unique to avoid multiple controllers reporting to the same metric
goroutine 1 [running]:
github.com/samber/lo.must({0x10532eec0, 0x1400089f4a0}, {0x0, 0x0, 0x0})
/Users/joinnis/go/pkg/mod/github.com/samber/lo@v1.47.0/errors.go:53 +0x1cc
github.com/samber/lo.Must0(...)
/Users/joinnis/go/pkg/mod/github.com/samber/lo@v1.47.0/errors.go:72
sigs.k8s.io/karpenter/pkg/operator.(*Operator).WithControllers(0x140008a3080, {0x1058d5640, 0x1400081b4a0}, {0x14000eaaa80?, 0x1058e82e0?, …
```

Apply unique controller name to each registration of status controller

---

metrics/emf.go
metrics/metrics.go
metrics/multi.go
metrics/prometheus.go
metrics/types.go
mock/atomic.go
mock/function.go
status/controller.go

This change wraps the prometheus metric using an interface so that we can build multiple metric paths into the metrics that we publish. By default, we will route the metrics to prometheus but since the variables are exposed externally, users can modify the metric to create their own metric pipeline.
For instance
```
status.TerminationDuration = pmetrics.NewMultiObservation(
status.TerminationDuration,
pmetrics.NewEMFObservation(writer, "operatorpkg", "operator_termination_duration_seconds", []string{"group", "kind", "namespace"}),
)
```

feat: Add interface functions for prometheus metrics to extend to other metric types

---

status/controller.go
status/controller_test.go
status/metrics.go

We shouldn't have included namespace/name in our histogram counters since this is going to significantly increase the cardinality for our resources

fix: Drop namespace name from operatorpkg counter

---

metrics/emf.go

Drop default empty dimension set in the EMF metric builder since we can explicitly pass the empty dimension set to the set of dimensions that we use in the builder if we truly need the empty set.

chore: Drop default empty dimension set

---

status/controller.go
status/controller_test.go
status/metrics.go
status/unstructured_adapter.go
status/unstructured_adapter_test.go

Issue https://github.com/awslabs/operatorpkg/issues/87
Auto-gen metric names based on the kind that is passed into the controller. The system for the metric will be `operator` and subsystem is `<object kind>_status_condition`. The labels used are the same statically defined metrics, with exception of the kind label, that was removed. These new metrics can be enabled using the controller options passed at controller creation. The new auto generated metrics will look as such:
- operator_<object kind>_status_condition_transitions_total
- operator_<object kind>_status_condition_transition_seconds
- operator_<object kind>_status_condition_current_status_seconds
- operator_<object kind>_status_condition_count
- operator_<object kind>_termination_current_time_seconds
- …

feat: Add Object Specific Metric for Status Condition Controller

---

leaderelection/leasehijacker.go

Enables support for developers to steal leases from a running controller.
```
LeaderElectionResourceLockInterface: leaderelection.LeaseHijacker(ctx, controllerruntime.GetConfigOrDie(), "kube-system", name),
```
```
rnal.go:512     error received after stop sequence was engaged      {"error": "leader election lost"}
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
/home/etarn/workspaces//tmp/gomodcache/sigs.k8s.io/controller-runtime@v0.19.1/pkg/manager/internal.go:512
2024-11-14T22:44:59.137Z        INFO    leaderelection/leasehijacker.go:24  hijacking lease {"namespace": "kube-system", "name": "controller"}
2024-11-14T22:45:01.067Z        INFO    controller-runtime.metrics  server/server.go:208 …
```

feat: Implemented leaderelection.LeaseHijacker

---

events/controller.go
events/metrics.go

- Removing kind and group labels
- These labels are redundant since the metric name is based on the object 

chore: Redundant labels from events controller

---

status/controller.go

Store object in map during object termination. Because we were not storing the older version of the object, we were not able to get additional properties from the object during object termination. This fixes the code so that we store the object and can grab additional properties.
Note: This also fixes a resource leak that was introduced with the terminatingObjects map

fix: Store object in map on object termination and fix resource leak

---

status/controller.go
status/controller_test.go

We should be deleting the current status and status count metrics when we get a change in reason. This should not change the amount of time that a status condition is in a given status, but should ensure that we don't leak metrics when the reason changes but the status doesn't
Note that there are some states that are left behind (like status=`Unknown`, reason=`AwaitingReconciliation`) even though the NodeClaim is currently `True` for all conditions
```
operator_nodeclaim_status_condition_current_status_seconds{karpenter_k8s_aws_ec2nodeclass="default",karpenter_sh_nodepool="default",name="default-v7bnf",namespace="",reason="AwaitingReconciliation",status="Unknown",type="Initialized"} 30.050751174 …
```

fix: Delete partial match if reason changes

---

test/expectations/expectations.go

Updating ExpectDelete to ignores already deleted objects

Updating ExpectDelete to ignores already deleted objects

---

README.md

Fix typo to the new Karpenter repo moved to CNCF.

Update README.md fixing karpenter repo name

---

test/expectations/expectations.go

Adds `GinkgoHelper()` to functions that didn't have it -- causing error messages that were confusing due to Ginkgo error message not being linked to the caller of the expectation function

chore: Add GinkgoHelper to expectations that were missing it

---

env/env.go

Add env helper funcs to operatorpkg. These funcs are basically just an improvement on the existing `os` functions that get from environment variables by adding automatic defaulting to them

chore: Add env defaulting funcs to operatorpkg

---

test/expectations/expectations.go

Adds two expectations for checking if a reconciler has requeued based on a provided `reconcile.Result`. A motivating example can be found in this PR: https://github.com/kubernetes-sigs/karpenter/pull/1876.

feat: add expectations for reconciler requeue

---

status/controller.go

We weren't deleting from `observedConditions` when the object gets deleted. This meant that we would maintain this key in the map forever.
`make presubmit`

fix: Fix a leak associated with not deleting from observedConditions

---

status/condition_set.go
status/condition_set_test.go

…
If a status condition is changed to true while the object is deleting, the root condition will transition to unknown as all the dependent conditions as from previous generation. We bump the generation of all the conditions so that the root condition remains the same as it was.

Bump all obersved generation version of all conditions when object is deleting

---

go.mod
serrors/logger.go
serrors/serrors.go

This change adds the `serrors` package which allows callers to create structured errors with key/value pairs for better structured logging. Wrapping errors with `serrors.Wrap` will add values. If the error is wrapped multiple times, key/value pairs will be pulled out when the error is unwrapped during logging
```
for _, val := range req.Values {
it, err := c.getInstanceType(val)
if err != nil {
return nil, serrors.Wrap(fmt.Errorf("instance type not found"), "instance-type", val)
}
...
}
```
```
{"level":"ERROR","time":"2025-04-14T06:49:10.528Z","logger":"controller","caller":"cloudprovider/cloudprovider.go:81","message":"failed launching nodeclaim","commit":"8da13bb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","cont …
```

chore: Add the structured error package (`serrors`)

---

aws/middleware/middleware.go

Update the middleware to handle parsing out all details from AWS API errors, not just the request ID

chore: Modify error handler middleware to return structured errors

---

status/controller.go

Allow specifying just GaugeLabels in the `status.Controller` for metric labels with high cardinality

chore: Allow specifying labels only for gauges

---

go.mod
serrors/serrors.go
serrors/suite_test.go

Support structured errors for `multierr.Append` and `multierr.Combine`. `multierr` is more challenging because multiple structured errors can be packed together. Additionally, it's lucky that errors in a multierr have the same values. As a result, `serrors.UnwrapValues()` combines elements with the same key together into a single array of values mapped to a single key. We keep the keyed values inside the call to `Error()` to ensure that the context around the key/value is retained

chore: Support structured errors for multierr

---

status/controller.go
status/controller_test.go
test/object.go

This adds the `WithFields()` and `WithGaugeFields()` options to the status controller to allow pulling information out of the object and injecting it into the prometheus labels

chore: Add WithFields option to status controllers

---

status/controller.go
status/unstructured_adapter.go
status/unstructured_adapter_test.go
unstructured/unstructured.go

This change ensures we only convert partial portions of the objects when we convert them to Unstructured so we don't use large portions of memory for really large objects.

perf: Use partial unstructured converter to reduce memory consumption

---

test/expectations/expectations.go

Related to this PR https://github.com/kubernetes-sigs/karpenter/pull/2368
Some expectations are not ready to be used with karpenter.

test: refactor expectations to support karpenter project
